// Code generated by MockGen. DO NOT EDIT.
// Source: /home/saimon/Documents/Hubly/pulse/internal/app/repository/whatsApp.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	valueobject "github.com/inter-hubly/pulse/internal/domain/valueobject"
)

// MockWhatsApp is a mock of WhatsApp interface.
type MockWhatsApp struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppMockRecorder
}

// MockWhatsAppMockRecorder is the mock recorder for MockWhatsApp.
type MockWhatsAppMockRecorder struct {
	mock *MockWhatsApp
}

// NewMockWhatsApp creates a new mock instance.
func NewMockWhatsApp(ctrl *gomock.Controller) *MockWhatsApp {
	mock := &MockWhatsApp{ctrl: ctrl}
	mock.recorder = &MockWhatsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsApp) EXPECT() *MockWhatsAppMockRecorder {
	return m.recorder
}

// GetAllMessage mocks base method.
func (m *MockWhatsApp) GetAllMessage(ctx context.Context, id, toId string) ([]*valueobject.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMessage", ctx, id, toId)
	ret0, _ := ret[0].([]*valueobject.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMessage indicates an expected call of GetAllMessage.
func (mr *MockWhatsAppMockRecorder) GetAllMessage(ctx, id, toId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMessage", reflect.TypeOf((*MockWhatsApp)(nil).GetAllMessage), ctx, id, toId)
}
